trigger:
- main

pool:
  name: MySelfHostedPool

variables:
  imageName: 'aml-ui-dashboard'
  acrLoginServer: 'acrall.azurecr.io'
  tag: '$(Build.BuildId)'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    docker buildx create --use || true
    docker buildx build --platform linux/amd64 \
      -t $(acrLoginServer)/$(imageName):$(tag) \
      -t $(acrLoginServer)/$(imageName):latest \
      --push .
  displayName: 'Build and push Docker image'

- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'sc-new' # your service connection name
    azureResourceGroup: 'devops-connection'
    kubernetesCluster: 'aks-all'
    useClusterAdmin: true
    namespace: 'default'
    command: apply
    useConfigurationFile: true
    configuration: 'manifests/deployment.yaml'
