trigger:
- main

pool:
  name: MySelfHostedPool  # Change this to the name of your agent pool if you use a custom one

variables:
  imageName: 'aml-ui-dashboard'  # Image name (can change if needed)
  acrLoginServer: 'acrall.azurecr.io'

steps:
# Checkout code
- checkout: self

# Install Node.js and build
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Azure CLI login (needed for ACR login)
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc-new'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name acrall

# Build and Push to ACR
- script: |
    docker build -f project-deploy/Dockerfile -t $(acrLoginServer)/$(imageName):$(Build.BuildId) project-deploy
    docker push $(acrLoginServer)/$(imageName):$(Build.BuildId)
  displayName: 'Build and Push Docker Image to ACR'

# Deploy to AKS
- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'sc-new'
    azureResourceGroup: 'devops-connection'
    kubernetesCluster: 'aks-all'
    namespace: 'default'
    command: apply
    useConfigurationFile: true
    configuration: 'k8s/deployment.yaml'
