trigger:
  - main

pool:
  name: MySelfHostedPool  # Your self-hosted agent pool

variables:
  imageName: 'aml-ui-dashboard'
  acrLoginServer: 'acrallnew.azurecr.io'  # ACR login server
  tag: '$(Build.BuildId)'
  azureSubscription: 'sc-new'  # Your Azure service connection name
  acrName: 'acrallnew'  # ACR name
  resourceGroup: 'devops-connection'
  aksCluster: 'aks-all'

steps:
# Checkout source code
- checkout: self

# Install Node.js (for building the frontend)
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies and build
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Authenticate to ACR using Azure CLI
- task: AzureCLI@2
  displayName: 'Login to ACR'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $(acrName)

# Build and push Docker image to ACR with multi-platform support (amd64 and arm64)
- script: |
    docker buildx create --use || true  # Create and use a builder instance if not already available
    docker buildx build --platform linux/amd64,linux/arm64 \
      -t $(acrLoginServer)/$(imageName):$(tag) \
      -t $(acrLoginServer)/$(imageName):latest \
      --push .  # Push images to ACR
  displayName: 'Build and push multi-platform Docker image to ACR'

# Deploy to AKS using kubectl
- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: '$(azureSubscription)'
    azureResourceGroup: '$(resourceGroup)'
    kubernetesCluster: '$(aksCluster)'
    useClusterAdmin: true
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deployment.yaml'
