apiVersion: apps/v1
kind: Deployment
metadata:
  name: aml-ui-dashboard
  namespace: default
  labels:
    app: aml-ui-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aml-ui-dashboard
  template:
    metadata:
      labels:
        app: aml-ui-dashboard
    spec:
      containers:
      - name: aml-ui-dashboard
        image: acrallnew.azurecr.io/aml-ui-dashboard:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: aml-ui-dashboard-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: aml-ui-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
