apiVersion: v1
kind: Service
metadata:
  name: aml-ui-dashboard-service
spec:
  selector:
    app: aml-ui-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Expose the service externally

